# Generated by Django 4.0 on 2022-08-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(blank=True, default='', max_length=75, verbose_name='B name')),
                ('gname', models.CharField(blank=True, default='', max_length=75, verbose_name='G name')),
            ],
        ),
    ]
